
# site
title: Dream City
description: A Developer's blog. 
keywords: thewei, develop, blog
rss: rss.xml
favicon: /icon.png

# site url. you can set as 'http://yoursite.com/child' if need
# please add 'http://' or 'https://'
url: http://thewei.github.io/blog

# comment
comment:
    disqus: thewei
#    duoshuo:

# theme
theme: ccc45

# pagination
per_page: 3
archives_per_page: 30

#menu
menu:
    home: /
    about: /about
    # archives: /archives
    # tags: /tags
    # categories: /categories

# category
default_category: uncategorized

# html output directory or child directory e.g. 'child'
public_dir: /

# category directory
category_dir:

# tag directory
tag_dir:

# site content issue
# username/repository
issue_repo: thewei/thewei.github.com

# thumbnail mode 
# 1: use the first image as thumbnail and remove the image
# 2: use the first image as thumbnail but not remove the image
thumbnail_mode: 2

# thumbnail size
# whether to get the thumbnail size
thumbnail_size: false

# site post authors filter
authors:
#    - LoeiFy
#    - author0
#    - author1

# custom fields
customs: 
#    - test
#    - title

# GitHub access token(Optional)
# token should be separated by whitespace if you push this file to GitHub 
# token: sd46a6d65a asd8sdbn

# dev mode
# boolean / string
# you can set test json path: test/test.json 
dev: false
